image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - mkdir build && cmake -S . -B build
    - cmake --build build -j
  artifacts:
    untracked: true
    expire_in: 30 days
    paths:
      - "./build"
test:
  stage: test
  dependencies:
    - build
  before_script:
    - apt update && apt -y install cmake
  script:
    - cd build && ctest --output-on-failure -j
